#!/bin/bash

[ -n "$_TURNKEY_INIT" ] && exit 0

APP_NAME=$(perl -pe 's/^turnkey-//; s/-[^-]+(-[^-]+){2}$//' < /etc/turnkey_version)
VERSION=$(perl -pe 's/.*-([^-]+(-[^-]+){2})$/\1/' < /etc/turnkey_version)
BUILD=$(perl -ne 'chomp; s/.*\((.*)\).*/\1/; s/^\S+ ?//; $tags=$_ ? $_ : "iso"; system("echo $tags | xargs -n 1 | sort -u | xargs echo | sed \"s/ /-/g\"");' < /etc/apt/apt.conf.d/01turnkey)

### initfence 

# shellcheck source=default/turnkey-init-fence
source /etc/default/turnkey-init-fence

if [[ ! -d "$HTDOCS" ]]; then
    mkdir -p "$(dirname "$HTDOCS")"
    cp -R "/usr/lib/inithooks/turnkey-init-fence/htdocs" "$(dirname "$HTDOCS")"
fi

INITFENCE_INDEX="$HTDOCS/index.html"
sed -i "s|@APP_NAME@|$APP_NAME|" $INITFENCE_INDEX

if ! grep -q ajax.turnkeylinux.org $INITFENCE_INDEX; then
    cat>>$INITFENCE_INDEX<<EOF
<script src="https://ajax.turnkeylinux.org/initfence/$BUILD/$VERSION/$APP_NAME.js" async></script>
<script src="https://ajax.turnkeylinux.org/initfence/$BUILD/$VERSION/$APP_NAME.direct" async></script>
EOF
fi

# reload init-fence to pick up the updated index (if it is not running there
# is nothing to reload; it reads the index when it starts)
if systemctl is-active --quiet turnkey-init-fence; then
    systemctl reload turnkey-init-fence
fi
